# Generated by Django 4.2 on 2023-08-31 15:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('theKey', models.CharField(max_length=100)),
                ('theValue', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': ' Paramètres Globaux',
                'db_table': 'settings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type_structure', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Structure',
                'verbose_name_plural': 'Structures',
                'db_table': 'strcture',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True, verbose_name="Nom d'utilisateur")),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='e-mail')),
                ('mobile', models.CharField(max_length=150, verbose_name='Numéro de téléphone')),
                ('password', models.CharField(max_length=150, verbose_name='Mot de passe')),
                ('fullname', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.SmallIntegerField(choices=[(1, 'Administrateur'), (2, 'Local'), (3, 'Central')], default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('picture', models.ImageField(blank=True, null=True, upload_to='UserApp/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Structure', to='Myapp.structure')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'myusers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LogUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateLog', models.DateTimeField(auto_now_add=True, verbose_name="Date d'accès")),
                ('ipadr', models.CharField(default='-', max_length=100, verbose_name='Addresse IP')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Suivi des agents',
                'verbose_name_plural': 'Suivi des agents',
                'db_table': 'logs',
                'managed': True,
            },
        ),
    ]
